services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  ttimbers/eg-tests-analysis:b7e1262
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64